name: Make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Dependencies installation
      run: |
        sudo apt update
        sudo apt install -y make

    - name: Make
      run: make

    - name: Check binaries
      run: |
        ls portoshim
        ls logshim
        if echo $(ldd logshim 2>&1) | grep -q "not a dynamic executable"; then
          echo "logshim is static"
        else
          exit 1
        fi
